version: '3.8'

services:
  # Initialize database if it doesn't exist
  kuzu-init:
    build:
      context: .
      dockerfile: Dockerfile.http
    volumes:
      - ./data:/database
    environment:
      - KUZU_MCP_DATABASE_PATH=/database
    command: |
      sh -c "
        if [ ! -d /database ] || [ -z \"\$(ls -A /database 2>/dev/null)\" ]; then
          echo '📦 Initializing new Kuzu database...'
          node dist/index.js --init /database --template movies
          echo '✅ Database initialized successfully!'
        else
          echo '✓ Database already exists, skipping initialization'
        fi
      "

  kuzu-mcp-http:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "3000:3000"
    volumes:
      # Mount your database directory here
      - ./data:/database
    environment:
      - KUZU_MCP_DATABASE_PATH=/database
      - KUZU_READ_ONLY=false
      - PORT=3000
    restart: unless-stopped
    # command: ["node", "dist/index.js", "--transport", "http", "--port", "8080", "--endpoint", "/kuzu"]
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/mcp').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      kuzu-init:
        condition: service_completed_successfully